// Mocks generated by Mockito 5.4.4 from annotations
// in love_cook/test/features/cooking/data/services/voice_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:love_cook/core/services/ai_proxy_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRealtimeTokenResponse_0 extends _i1.SmartFake
    implements _i2.RealtimeTokenResponse {
  _FakeRealtimeTokenResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AiProxyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiProxyService extends _i1.Mock implements _i2.AiProxyService {
  MockAiProxyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<Map<String, dynamic>> chatCompletions({
    required List<Map<String, dynamic>>? messages,
    String? model = r'gpt-4o-mini',
    double? temperature = 0.7,
    int? maxTokens,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chatCompletions,
          [],
          {
            #messages: messages,
            #model: model,
            #temperature: temperature,
            #maxTokens: maxTokens,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<_i2.RealtimeTokenResponse> getRealtimeToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRealtimeToken,
          [],
        ),
        returnValue: _i3.Future<_i2.RealtimeTokenResponse>.value(
            _FakeRealtimeTokenResponse_0(
          this,
          Invocation.method(
            #getRealtimeToken,
            [],
          ),
        )),
      ) as _i3.Future<_i2.RealtimeTokenResponse>);

  @override
  _i3.Future<bool> healthCheck() => (super.noSuchMethod(
        Invocation.method(
          #healthCheck,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String> audioTranscription({
    required _i4.Uint8List? audioData,
    required String? filename,
    String? language = r'zh',
    String? model = r'whisper-1',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #audioTranscription,
          [],
          {
            #audioData: audioData,
            #filename: filename,
            #language: language,
            #model: model,
          },
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #audioTranscription,
            [],
            {
              #audioData: audioData,
              #filename: filename,
              #language: language,
              #model: model,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<_i4.Uint8List> audioSpeech({
    required String? text,
    String? model = r'tts-1',
    String? voice = r'nova',
    String? responseFormat = r'mp3',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #audioSpeech,
          [],
          {
            #text: text,
            #model: model,
            #voice: voice,
            #responseFormat: responseFormat,
          },
        ),
        returnValue: _i3.Future<_i4.Uint8List>.value(_i4.Uint8List(0)),
      ) as _i3.Future<_i4.Uint8List>);

  @override
  _i3.Future<String?> imageGeneration({
    required String? prompt,
    String? model = r'dall-e-3',
    String? size = r'1024x1024',
    String? quality = r'standard',
    int? n = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #imageGeneration,
          [],
          {
            #prompt: prompt,
            #model: model,
            #size: size,
            #quality: quality,
            #n: n,
          },
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}
